### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by PeaceSfiSh**
I wasn't able to run this extension with your latest changes and made some adjustments.
- namespace for GeneralUtility was defined twice
- field "expire" was never set in SQL update statement
- second parameter for blacklist check was NULL, but an Array was required
- label for the module wasn't available, because of a folder name mismatch

Please contact me if something doesn't make sense.

### CODE REVIEW

**Comment by thomaszbz** [comment]
"namespace for GeneralUtility was defined twice": I had the same problem. It disappeared after flushing the system caches (via install tool).

**Comment by PeaceSfiSh** [comment]
Thanks for your feedback. IMHO a general clean up for the namespace usage is necessary.

**Comment by mblaschke** [comment]
I will check this request in the next days. Thanks :)

**Comment by mblaschke** [comment]
I've used Spaces because of PSR-2:
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md

I know that TYPO3 is using another coding style and there are already tracker-issues because of PSR-2 compatibility. But TYPO3 can't switch to PSR-2 because this would invalidate all pending merge requests.

Because of this i can't automatically merge this pull request :(
I will try to cherry-pick these commits.

**Comment by PeaceSfiSh** [comment]
What if you merge this pull request and do a 'git revert' afterwards?
Could you add the PSR-2 fact to the documentation, maybe add a 'Development' section?

**Comment by mblaschke** [comment]
Merged :)
Will hopefully have some time next weekend for next developments :)

**Pull request closed without merging**
