### PR TITLE
[BUGFIX] Use FontAwesome image as main module icon

### LINKED ISSUE #359: The SEO Icon in the navigation should be black/white
**MetaSEO version**: 2.0.3

**TYPO3 version**: 7.6.16

To be compatible with the overall layout of the backend, the SEO icon (to open and collapse the sub navigation) should be black/white.

### PR DESCRIPTION
**Pull request by simonschaufi**
Fixes #359

### CODE REVIEW

**Comment by thomaszbz** [comment]
We still support PHP 5.3 in 2.0.x releases (because we still support Typo3 6.2). Therfore, `array()` must still be used. Will be refactored in 3.0.0, all-at-once, once-forever.

**Comment by simonschaufi** [comment]
I could do a TYPO3 version check and only use that code if TYPO3 7 is used.

**Comment by thomaszbz** [comment]
`FontawesomeIconProvider` is not available in 6.2. Cannot be merged in 2.0.x that way.

**Comment by simonschaufi** [comment]
Please have a look at the latest commit

**Comment by thomaszbz** [comment]
Looks better now optically, at least for a merge in 2.0.x. Still need to review/test it.

**Comment by simonschaufi** [comment]
Tested with 6.2 and works for me

**Comment by thomaszbz** [comment]
Via PR #368:

- rebased patch set
- applied PSR-2 coding style
- removed `:class` for 5.3 compat
- added name to contributors list

**Comment by thomaszbz** [comment]
Merged via #368

**Pull request closed without merging**
