### PR TITLE
Reference to "wizard_element_browser" was migrated to new "wizard_link"

### PR DESCRIPTION
**Pull request by snduesel**
Reference to "wizard_element_browser" was migrated to new "wizard_link" for field "tx_metaseo_canonicalurl" in TCA table "pages_language_overlay"

### CODE REVIEW

**Comment by thomaszbz** [comment]
@snduesel Thanks for your contribution. Would be great if you could report back via #325 (need to figure out if this is pure refactoring and when we can merge it).

Fixes #325

**Comment by thomaszbz** [comment]
Blocked by dropping support for 6.2

**Comment by thomaszbz** [comment]
@snduesel why did you close your PR?

**Comment by snduesel** [comment]
You have blocked this PR?

**Comment by thomaszbz** [comment]
It's blocked just as long as support for TYPO3 6.2 is not dropped in metaseo. That can take a few months. My message was just for internal purposes to make sure that nobody merges it beforehand (and breaks our code for 6.2 users).

Basically that only means that we will merge it later. I really appreciate your contribution and would be glad if we can take it (just later).

**Comment by thomaszbz** [comment]
I restored your changes via PR #329. Sorry, there was no way for me to just reopen your PR or reference to your commit without the original branch.

**Comment by snduesel** [comment]
@thomaszbz no Problem

**Pull request closed without merging**
